import { describe, expect, it } from "vitest";
import { buildNormalizedComparisonMatrix } from "@/lib/analytics/ai/executive-intelligence/comparison-matrix-normalizer";
import type { ParticipationAnalyticsPayload } from "@/lib/achievement-participation-analytics";

const payload = (): ParticipationAnalyticsPayload => ({
  ok: true,
  generatedAt: "2026-01-01T00:00:00.000Z",
  filters: {},
  kpis: {
    totalParticipations: 40,
    distinctStudents: 30,
    mawhibaParticipationPct: 10,
    femalePct: 50,
    internationalSectionPct: 20,
    activeProgramsCount: 2,
    topProgramLabelAr: "—",
    topProgramLabelEn: "—",
    topSectionLabelAr: "—",
    topSectionLabelEn: "—",
    goldMedalCount: 3,
    firstPlaceCount: 1,
    nominationCount: 5,
    highestLevelLabelAr: "—",
    highestLevelLabelEn: "—",
    internationalAchievementPct: 10,
    globalAchievementPct: 5,
  },
  charts: {
    genderParticipation: [],
    sectionParticipation: [],
    mawhibaSplit: [],
    resultDistribution: [],
    levelDistribution: [],
    genderResultStack: [],
    topPrograms: [],
    activityHorizontal: [],
    resultOutcomeCompare: [],
    yearTrend: [],
  },
  activityOptions: [],
  focusedActivity: null,
  table: [
    {
      activityKey: "k-g7",
      activityLabelAr: "كانجارو",
      activityLabelEn: "Kangaroo",
      typeKey: "kangaroo",
      typeLabelAr: "c",
      typeLabelEn: "c",
      classificationKey: "c",
      classificationLabelAr: "c",
      classificationLabelEn: "c",
      levelKey: "g7",
      levelLabelAr: "سابع",
      levelLabelEn: "G7",
      participationResultKey: "p",
      participationResultAr: "p",
      participationResultEn: "p",
      totalParticipations: 15,
      distinctParticipants: 12,
      maleParticipants: 8,
      femaleParticipants: 4,
      arabicParticipants: 12,
      internationalParticipants: 3,
      mawhibaParticipants: 2,
      nonMawhibaParticipants: 10,
      goldMedalCount: 2,
      silverMedalCount: 1,
      bronzeMedalCount: 0,
      rankCount: 0,
      nominationCount: 0,
      participationOnlyCount: 10,
      approvedAchievements: 5,
      excellenceRatePct: 40,
    },
    {
      activityKey: "custom-g8",
      activityLabelAr: "نشاط خاص",
      activityLabelEn: "Custom Event",
      typeKey: "custom",
      typeLabelAr: "c",
      typeLabelEn: "c",
      classificationKey: "c",
      classificationLabelAr: "c",
      classificationLabelEn: "c",
      levelKey: "g8",
      levelLabelAr: "ثامن",
      levelLabelEn: "G8",
      participationResultKey: "p",
      participationResultAr: "p",
      participationResultEn: "p",
      totalParticipations: 8,
      distinctParticipants: 6,
      maleParticipants: 4,
      femaleParticipants: 2,
      arabicParticipants: 6,
      internationalParticipants: 0,
      mawhibaParticipants: 0,
      nonMawhibaParticipants: 6,
      goldMedalCount: 0,
      silverMedalCount: 0,
      bronzeMedalCount: 0,
      rankCount: 0,
      nominationCount: 0,
      participationOnlyCount: 8,
      approvedAchievements: 2,
      excellenceRatePct: 10,
    },
  ],
  tableTotal: 2,
  page: 1,
  pageSize: 500,
});

describe("buildNormalizedComparisonMatrix", () => {
  it("builds columns from taxonomy and raw slug fallback", () => {
    const model = buildNormalizedComparisonMatrix(
      [{ year: 2024, payload: payload() }],
      true
    );

    expect(model).not.toBeNull();
    expect(model!.columnLabels.length).toBeGreaterThanOrEqual(2);
    expect(model!.rowLabels.length).toBeGreaterThan(0);
  });
});
