import { escapeHtml } from "@/lib/pdf/executive-pdf-escape";

export type ExecutivePdfMetadata = {
  generatedAtIso: string;
  generatedBy?: string;
  filtersSummary?: string;
  activityFocus?: string;
  reportPreset?: string;
  confidentiality?: string;
  correlationId?: string;
  aggregationVersion?: number;
  snapshotVersion?: number;
  trustStatus?: string;
  degradedExport?: boolean;
  analyticsBuildId?: string;
  datasetVersion?: number;
  filterHash?: string;
  canonicalFilterHash?: string;
  queryHash?: string;
};

export const formatExecutivePdfMetadataHtml = (
  isAr: boolean,
  meta: ExecutivePdfMetadata | undefined
): string => {
  if (!meta) return "";
  const metaRows = (
    [
      [isAr ? "تاريخ الإنشاء (ISO)" : "Generated at (ISO)", meta.generatedAtIso],
      meta.correlationId ? [isAr ? "معرّف التصدير" : "Export correlation id", meta.correlationId] : null,
      meta.generatedBy ? [isAr ? "أنشأه" : "Generated by", meta.generatedBy] : null,
      meta.filtersSummary ? [isAr ? "ملخص الفلاتر" : "Filters summary", meta.filtersSummary] : null,
      meta.activityFocus ? [isAr ? "تركيز النشاط" : "Activity focus", meta.activityFocus] : null,
      meta.reportPreset ? [isAr ? "قالب التقرير" : "Report preset", meta.reportPreset] : null,
      meta.confidentiality ? [isAr ? "تصنيف السرية" : "Confidentiality level", meta.confidentiality] : null,
      meta.aggregationVersion != null ?
        [isAr ? "إصدار التجميع" : "Aggregation version", String(meta.aggregationVersion)]
      : null,
      meta.snapshotVersion != null ?
        [isAr ? "إصدار اللقطة" : "Snapshot version", String(meta.snapshotVersion)]
      : null,
      meta.trustStatus ? [isAr ? "حالة الموثوقية" : "Trust status", meta.trustStatus] : null,
      meta.analyticsBuildId ?
        [isAr ? "معرّف التحليلات" : "Analytics build id", meta.analyticsBuildId]
      : null,
      meta.datasetVersion != null ?
        [isAr ? "إصدار مجموعة البيانات" : "Dataset version", String(meta.datasetVersion)]
      : null,
      meta.filterHash ? [isAr ? "بصمة الفلاتر" : "Filter hash", meta.filterHash] : null,
      meta.canonicalFilterHash && meta.canonicalFilterHash !== meta.filterHash ?
        [isAr ? "بصمة الفلاتر الموحدة" : "Canonical filter hash", meta.canonicalFilterHash]
      : null,
      meta.queryHash ? [isAr ? "بصمة الاستعلام" : "Query hash", meta.queryHash] : null,
      meta.degradedExport ?
        [isAr ? "وضع التصدير" : "Export mode", isAr ? "مخفّض" : "Degraded"]
      : null,
    ] as Array<[string, string] | null>
  ).filter((x): x is [string, string] => Array.isArray(x));
  if (metaRows.length === 0) return "";
  return `<div class="ep-meta-block"><table class="ep-meta-grid">${metaRows
    .map(
      ([k, v]) =>
        `<tr><th>${escapeHtml(k)}</th><td dir="auto">${escapeHtml(v)}</td></tr>`
    )
    .join("")}</table></div>`;
};
