export type TrainingFinalReportTemplateContext = {
  studentName: string;
  school: string;
  institutionName: string;
  opportunityTitle: string;
  trainingStartDate: string;
  trainingEndDate: string;
  trainingHours: string;
  assignedTasks: string;
  studentSection?: {
    practicalBenefitScore: number;
    objectivesClarityScore: number;
    supervisionQualityScore: number;
    workEnvironmentScore: number;
    relevanceScore: number;
    overallSatisfactionScore: number;
    skillsLearned: string;
    majorTasksCompleted: string;
    improvementSuggestions: string;
    mostValuableExperience: string;
    recommendToStudents: boolean;
    videoUrl?: string;
    imageEvidence?: Array<{ label?: string; caption?: string; fileName: string }>;
  };
  institutionSectionComplete?: boolean;
  scores: {
    attendance: number;
    punctuality: number;
    instructionCompliance: number;
    workEthics: number;
    responsibility: number;
    professionalism: number;
    communication: number;
    teamwork: number;
    initiative: number;
    learningSpeed: number;
    taskExecution: number;
    workQuality: number;
    safetyCompliance: number;
  };
  passedTraining: boolean;
  recommendFutureTraining: boolean;
  recommendEmployment: boolean;
  topAchievements: string;
  strengths: string;
  improvementAreas: string;
  finalRecommendation: string;
  supervisorName: string;
  supervisorTitle: string;
  supervisorPhone: string;
  generatedAt: string;
};
